import os

HERE = os.path.dirname(os.path.abspath(__file__))

ESSENTIA_MODELS_PATH = os.path.join(HERE, "essentia_models")
print(ESSENTIA_MODELS_PATH)

MOOD_LABELS = [
    "action",
    "adventure",
    "advertising",
    "background",
    "ballad",
    "calm",
    "children",
    "christmas",
    "commercial",
    "cool",
    "corporate",
    "dark",
    "deep",
    "documentary",
    "drama",
    "dramatic",
    "dream",
    "emotional",
    "energetic",
    "epic",
    "fast",
    "film",
    "fun",
    "funny",
    "game",
    "groovy",
    "happy",
    "heavy",
    "holiday",
    "hopeful",
    "inspiring",
    "love",
    "meditative",
    "melancholic",
    "melodic",
    "motivational",
    "movie",
    "nature",
    "party",
    "positive",
    "powerful",
    "relaxing",
    "retro",
    "romantic",
    "sad",
    "sexy",
    "slow",
    "soft",
    "soundscape",
    "space",
    "sport",
    "summer",
    "trailer",
    "travel",
    "upbeat",
    "uplifting",
]
MOOD_THRESHOLD = 0.63

GENRE_LABELS = [
    "60s",
    "70s",
    "80s",
    "90s",
    "acidjazz",
    "alternative",
    "alternativerock",
    "ambient",
    "atmospheric",
    "blues",
    "bluesrock",
    "bossanova",
    "breakbeat",
    "celtic",
    "chanson",
    "chillout",
    "choir",
    "classical",
    "classicrock",
    "club",
    "contemporary",
    "country",
    "dance",
    "darkambient",
    "darkwave",
    "deephouse",
    "disco",
    "downtempo",
    "drumnbass",
    "dub",
    "dubstep",
    "easylistening",
    "edm",
    "electronic",
    "electronica",
    "electropop",
    "ethno",
    "eurodance",
    "experimental",
    "folk",
    "funk",
    "fusion",
    "groove",
    "grunge",
    "hard",
    "hardrock",
    "hiphop",
    "house",
    "idm",
    "improvisation",
    "indie",
    "industrial",
    "instrumentalpop",
    "instrumentalrock",
    "jazz",
    "jazzfusion",
    "latin",
    "lounge",
    "medieval",
    "metal",
    "minimal",
    "newage",
    "newwave",
    "orchestral",
    "pop",
    "popfolk",
    "poprock",
    "postrock",
    "progressive",
    "psychedelic",
    "punkrock",
    "rap",
    "reggae",
    "rnb",
    "rock",
    "rocknroll",
    "singersongwriter",
    "soul",
    "soundtrack",
    "swing",
    "symphonic",
    "synthpop",
    "techno",
    "trance",
    "triphop",
    "world",
    "worldfusion",
]
GENRE_THRESHOLD = 0.63

ENGAGEMENT_LABELS = ["high", "low"]
ENGAGEMENT_THRESHOLD = 0.50

DANCEABLE_LABLES = ["True", "False"]
DANCEABLE_THRESHOLD = 0.50


LABELS = [
    "Chill",
    "Energetic",
    "Intense",
    "Uplifting",
    "Dark",
    "Melancholic",
    "Playful",
    "Romantic",
    "Workout",
    "Relaxation",
    "Study",
    "Driving",
    "Party",
    "Focus",
    "Meditation",
    "Nature",
]
